DROP DATABASE IF EXISTS `GYM`;
CREATE SCHEMA `GYM`;
USE `GYM`;

drop table if exists MEMBERS;
drop table if exists TRAINERS;
drop table if exists MACHINE;
drop table if exists COURSE;
drop table if exists GYM_PRODUCTS;
drop table if exists WORKS_FOR;
drop table if exists MEMBER_ADDRESS;
drop table if exists TRAINER_ADDRESS;
drop table if exists BUYS;
drop table if exists CLOTHES;
drop table if exists SHOES;
drop table if exists FOOD;

create table TRAINERS(
	TID VARCHAR(30),
	Fname VARCHAR(30) NOT NULL, 
	Mname VARCHAR(30), 
	LName VARCHAR(30),
	Weight INT,
	Gender VARCHAR(30),
	Age INT,
	Salary INT,
	Level INT,
	PRIMARY KEY(TID)
);
create table COURSE(
	CID VARCHAR(30),
	Fees INT,
	Duration VARCHAR(30),
	TID VARCHAR(30),
	PRIMARY KEY(CID),
	FOREIGN KEY(TID) REFERENCES TRAINERS(TID) ON DELETE CASCADE ON UPDATE CASCADE
);
create table MEMBERS(
	MID VARCHAR(30),
	Fname VARCHAR(30) NOT NULL, 
	Mname VARCHAR(30), 
	LName VARCHAR(30),
	Weight INT,
	Gender VARCHAR(30),
	DOB VARCHAR(30),
	Age INT,
	CID VARCHAR(30),
	TID VARCHAR(30),
	PRIMARY KEY(MID),
	FOREIGN KEY(CID) REFERENCES COURSE(CID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(TID) REFERENCES TRAINERS(TID) ON DELETE CASCADE ON UPDATE CASCADE
);


create table MACHINE(
	XID VARCHAR(30),
	Brand VARCHAR(30),
	AVG_CAL_per_HR VARCHAR(30),
	ELECTRICTY_CONSUMPTION VARCHAR(30),
	PRIMARY KEY(XID)

);

create table GYM_PRODUCTS(
	PID VARCHAR(30),
	Cost INT,
	Type VARCHAR(30),
	PRIMARY KEY(PID)
);
create table CLOTHES(
	PID VARCHAR(30),
	Type VARCHAR(30),
	Size VARCHAR(30),
	FOREIGN KEY(PID) REFERENCES GYM_PRODUCTS(PID) ON DELETE CASCADE ON UPDATE CASCADE
);
create table SHOES(
	PID VARCHAR(30),
	Brand VARCHAR(30),
	Size VARCHAR(30),
	FOREIGN KEY(PID) REFERENCES GYM_PRODUCTS(PID) ON DELETE CASCADE ON UPDATE CASCADE
);
create table FOOD(
	PID VARCHAR(30),
	Brand VARCHAR(30),
	Calorie VARCHAR(30),
	FOREIGN KEY(PID) REFERENCES GYM_PRODUCTS(PID) ON DELETE CASCADE ON UPDATE CASCADE
);
create table WORKS_FOR(
	MID VARCHAR(30),
	TID VARCHAR(30),
	CID VARCHAR(30),
	XID VARCHAR(30),
	HOURS INT,
	FOREIGN KEY(MID) REFERENCES MEMBERS(MID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(XID) REFERENCES MACHINE(XID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(CID) REFERENCES COURSE(CID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(TID) REFERENCES TRAINERS(TID) ON DELETE CASCADE ON UPDATE CASCADE
);
create table MEMBER_ADDRESS(
	MID VARCHAR(30),
	Street VARCHAR(30),
	Locality VARCHAR(30),
	FOREIGN KEY(MID) REFERENCES MEMBERS(MID) ON DELETE CASCADE ON UPDATE CASCADE
);
create table TRAINER_ADDRESS(
	TID VARCHAR(30),
	Street VARCHAR(30),
	Locality VARCHAR(30),
	FOREIGN KEY(TID) REFERENCES TRAINERS(TID) ON DELETE CASCADE ON UPDATE CASCADE
);
create table BUYS(
	MID VARCHAR(30),
	PID VARCHAR(30),
	FOREIGN KEY(MID) REFERENCES MEMBERS(MID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(PID) REFERENCES GYM_PRODUCTS(PID) ON DELETE CASCADE ON UPDATE CASCADE
);











